name: Build and Deploy Flutter Web to Azure SWA

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --fund=false
          else
            npm i --no-audit --fund=false
          fi

      - name: Bundle MSAL/Graph helper into build/web
        run: npx esbuild src/services/sharepointUpload.ts --bundle --format=iife --outfile=build/web/msal-sharepoint.js

      - name: Validate SWA token secret
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "Missing GitHub Actions secret: AZURE_STATIC_WEB_APPS_API_TOKEN" >&2
            echo "Add it in: Settings > Secrets and variables > Actions > New repository secret" >&2
            exit 1
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: .
          output_location: build/web
          skip_app_build: true
